import type { Metadata } from "next";
import "./globals.css";
import IframeHeightManager from "../components/IframeHeightManager";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Check if running on localhost
    const isLocalhost = typeof window !== 'undefined' &&
        (window.location.hostname === 'localhost' ||
            window.location.hostname === '127.0.0.1' ||
            window.location.hostname === '');

    const paddingClasses = isLocalhost ? 'pt-12 pb-20' : '';

    return (
        <html lang="en">
            <body className={`antialiased ${paddingClasses}`}>
                <div
                    id="main-content"
                    style={{ height: "auto", minHeight: "0", overflow: "visible" }}
                >
                    {children}
                </div>
                <IframeHeightManager />
            </body>
        </html>
    );
}