// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import IframeHeightManager from "@/components/IframeHeightManager";
import ViewportToaster from "@/components/ViewportToaster";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className="antialiased">
                <div
                    id="main-content"
                    style={{ height: "auto", minHeight: "0", overflow: "visible" }}
                >
                    {children}
                </div>
                <IframeHeightManager />
                <ViewportToaster />
            </body>
        </html>
    );
}